name: shacl validation

on:
  push:
    branches:
    - develop-3.0.0
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
        path: main
    - name: Validate against SHACL shape
      run: | 
           ls -la
           pip install pyshacl
           python3 -m pyshacl  -s shapes/shape1.ttl shapes/shape1-data.ttl
